#!/bin/bash

set -x

if [ ! -f $OPENSHIFT_DATA_DIR/nave/nave.sh ]; then
  git clone git://github.com/isaacs/nave.git $OPENSHIFT_DATA_DIR/nave
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle ]
  then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
  then
    cd $OPENSHIFT_DATA_DIR
    mkdir logs
fi

NAVE=$OPENSHIFT_DATA_DIR/nave/nave.sh

cd $OPENSHIFT_REPO_DIR/lnksmgmt-service/src/main/resources/public
HOME=$OPENSHIFT_DATA_DIR SHELL=/bin/bash $NAVE use 0.10.25 npm install --production
HOME=$OPENSHIFT_DATA_DIR SHELL=/bin/bash $NAVE use 0.10.25 node_modules/.bin/bower install --config.interactive=false --production

cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-2.7
export PATH=$GRADLE_HOME/bin:$PATH

gradle clean bootRepackage
