#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

cd $OPENSHIFT_REPO_DIR
nohup java -Xms384m -Xmx412m -jar lnksmgmt-service/build/libs/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift &
